DELETE    http://localhost:8080/events/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhZ2VtZ2lzaWxhQGdtYWlsLmNvbSIsImV4cCI6MTczMzk5NzQyMCwidXNlcklkIjowfQ.eMao4wbTAzklCD2aBjI2e88IyreCLcNZAor1omRUzBs

